// src/lib/mock-data.ts (ajouter à la fin du fichier existant)

export type LegalDocument = {
  id: string;
  title: string;
  reference: string;
  type: 'Loi' | 'Décret' | 'Arrêté' | 'Ordonnance';
  category: string;
  publicationDate: string;
  summary: string;
  illustration?: string;
  pdfSize: string;
  pageCount: number;
  tags: string[];
};

// Données simulées pour les textes juridiques
export const mockLegalDocuments: LegalDocument[] = [
  {
    id: '1',
    title: 'Code du Travail de Madagascar',
    reference: 'Loi n° 2003-044',
    type: 'Loi',
    category: 'Droit du travail',
    publicationDate: '28 Juillet 2004',
    summary: 'Le Code du Travail régit les relations entre employeurs et travailleurs. Il définit les conditions de travail, les contrats, les congés, les salaires minimum, et les procédures de licenciement.',
    illustration: '⚖️',
    pdfSize: '2.4 MB',
    pageCount: 156,
    tags: ['Travail', 'Emploi', 'Contrats', 'Salaire'],
  },
  {
    id: '2',
    title: 'Loi sur la protection des données personnelles',
    reference: 'Loi n° 2014-038',
    type: 'Loi',
    category: 'Numérique et données',
    publicationDate: '07 Janvier 2015',
    summary: 'Cette loi encadre la collecte, le traitement et la conservation des données personnelles à Madagascar. Elle garantit le droit à la vie privée et à la protection des informations personnelles.',
    illustration: '🔒',
    pdfSize: '856 KB',
    pageCount: 42,
    tags: ['Données', 'Vie privée', 'RGPD', 'Numérique'],
  },
  {
    id: '3',
    title: 'Code pénal malgache',
    reference: 'Loi n° 2004-020',
    type: 'Loi',
    category: 'Droit pénal',
    publicationDate: '19 Août 2005',
    summary: 'Le Code pénal définit les infractions, les peines applicables et les procédures judiciaires. Il protège les personnes et les biens contre les actes criminels et délictueux.',
    illustration: '👮',
    pdfSize: '3.2 MB',
    pageCount: 234,
    tags: ['Pénal', 'Justice', 'Infractions', 'Sanctions'],
  },
  {
    id: '4',
    title: 'Loi sur le harcèlement sexuel en milieu professionnel',
    reference: 'Loi n° 2019-008',
    type: 'Loi',
    category: 'Droit du travail',
    publicationDate: '15 Mai 2019',
    summary: 'Cette loi définit et sanctionne le harcèlement sexuel au travail. Elle protège les victimes et impose des obligations aux employeurs pour prévenir ces comportements.',
    illustration: '🚫',
    pdfSize: '412 KB',
    pageCount: 18,
    tags: ['Harcèlement', 'Travail', 'Protection', 'Sanction'],
  },
  {
    id: '5',
    title: 'Code de la famille',
    reference: 'Loi n° 2007-022',
    type: 'Loi',
    category: 'Droit de la famille',
    publicationDate: '20 Août 2007',
    summary: 'Le Code de la famille régit le mariage, le divorce, la filiation, l\'autorité parentale, l\'adoption et les successions. Il protège les droits de chaque membre de la famille.',
    illustration: '👨‍👩‍👧‍👦',
    pdfSize: '1.8 MB',
    pageCount: 98,
    tags: ['Famille', 'Mariage', 'Divorce', 'Filiation'],
  },
  {
    id: '6',
    title: 'Décret sur le salaire minimum interprofessionnel garanti',
    reference: 'Décret n° 2023-456',
    type: 'Décret',
    category: 'Droit du travail',
    publicationDate: '12 Janvier 2023',
    summary: 'Ce décret fixe le montant du SMIG à Madagascar et les modalités de son application. Il protège les travailleurs contre des rémunérations trop faibles.',
    illustration: '💰',
    pdfSize: '245 KB',
    pageCount: 8,
    tags: ['SMIG', 'Salaire', 'Travail', 'Rémunération'],
  },
  {
    id: '7',
    title: 'Loi sur la protection de l\'enfant',
    reference: 'Loi n° 2007-023',
    type: 'Loi',
    category: 'Droits de l\'enfant',
    publicationDate: '20 Août 2007',
    summary: 'Cette loi garantit les droits fondamentaux de l\'enfant : éducation, santé, protection contre les abus, interdiction du travail des enfants. Elle transpose la Convention internationale des droits de l\'enfant.',
    illustration: '👶',
    pdfSize: '1.1 MB',
    pageCount: 64,
    tags: ['Enfant', 'Protection', 'Éducation', 'Santé'],
  },
  {
    id: '8',
    title: 'Décret d\'application sur les congés payés',
    reference: 'Décret n° 2006-178',
    type: 'Décret',
    category: 'Droit du travail',
    publicationDate: '14 Mars 2006',
    summary: 'Ce décret précise les modalités de calcul et d\'attribution des congés payés selon le Code du Travail. Il définit la durée minimale et les conditions d\'acquisition.',
    illustration: '🏖️',
    pdfSize: '328 KB',
    pageCount: 12,
    tags: ['Congés', 'Vacances', 'Travail', 'Repos'],
  },
  {
    id: '9',
    title: 'Loi sur l\'égalité entre hommes et femmes',
    reference: 'Loi n° 2015-012',
    type: 'Loi',
    category: 'Égalité et discrimination',
    publicationDate: '03 Juin 2015',
    summary: 'Cette loi promeut l\'égalité des genres dans tous les domaines : travail, éducation, politique. Elle sanctionne les discriminations fondées sur le sexe.',
    illustration: '⚖️',
    pdfSize: '678 KB',
    pageCount: 28,
    tags: ['Égalité', 'Genre', 'Discrimination', 'Femmes'],
  },
  {
    id: '10',
    title: 'Arrêté sur les normes de sécurité au travail',
    reference: 'Arrêté n° 2018-1234',
    type: 'Arrêté',
    category: 'Droit du travail',
    publicationDate: '22 Novembre 2018',
    summary: 'Cet arrêté fixe les normes minimales de sécurité et d\'hygiène que les employeurs doivent respecter pour protéger la santé et la sécurité des travailleurs.',
    illustration: '⚠️',
    pdfSize: '542 KB',
    pageCount: 24,
    tags: ['Sécurité', 'Hygiène', 'Travail', 'Prévention'],
  },
  {
    id: '11',
    title: 'Code de la consommation',
    reference: 'Loi n° 2012-006',
    type: 'Loi',
    category: 'Droit de la consommation',
    publicationDate: '18 Avril 2012',
    summary: 'Le Code de la consommation protège les consommateurs contre les pratiques commerciales déloyales, les clauses abusives et les produits dangereux. Il définit leurs droits et recours.',
    illustration: '🛒',
    pdfSize: '1.5 MB',
    pageCount: 72,
    tags: ['Consommation', 'Protection', 'Garantie', 'Recours'],
  },
  {
    id: '12',
    title: 'Loi sur le bail à loyer',
    reference: 'Loi n° 2005-018',
    type: 'Loi',
    category: 'Droit immobilier',
    publicationDate: '07 Septembre 2005',
    summary: 'Cette loi régit les relations entre propriétaires et locataires : conclusion du bail, loyer, charges, réparations, résiliation et expulsion. Elle protège les deux parties.',
    illustration: '🏠',
    pdfSize: '892 KB',
    pageCount: 38,
    tags: ['Location', 'Bail', 'Loyer', 'Logement'],
  },
  {
    id: '13',
    title: 'Ordonnance sur les procédures judiciaires simplifiées',
    reference: 'Ordonnance n° 2020-002',
    type: 'Ordonnance',
    category: 'Procédure judiciaire',
    publicationDate: '28 Février 2020',
    summary: 'Cette ordonnance simplifie certaines procédures judiciaires pour rendre la justice plus accessible. Elle réduit les délais et les formalités pour les litiges de faible montant.',
    illustration: '⚖️',
    pdfSize: '456 KB',
    pageCount: 16,
    tags: ['Justice', 'Procédure', 'Simplification', 'Accès'],
  },
  {
    id: '14',
    title: 'Loi sur la liberté d\'expression et de la presse',
    reference: 'Loi n° 2016-037',
    type: 'Loi',
    category: 'Libertés publiques',
    publicationDate: '11 Octobre 2016',
    summary: 'Cette loi garantit la liberté d\'expression et la liberté de la presse tout en définissant leurs limites : diffamation, injure, incitation à la haine. Elle protège aussi les journalistes.',
    illustration: '📰',
    pdfSize: '734 KB',
    pageCount: 32,
    tags: ['Expression', 'Presse', 'Liberté', 'Médias'],
  },
  {
    id: '15',
    title: 'Décret sur l\'aide juridictionnelle',
    reference: 'Décret n° 2010-345',
    type: 'Décret',
    category: 'Accès à la justice',
    publicationDate: '19 Juin 2010',
    summary: 'Ce décret définit les conditions d\'accès à l\'aide juridictionnelle gratuite pour les personnes à faibles revenus. Il précise les démarches et les pièces à fournir.',
    illustration: '🤝',
    pdfSize: '298 KB',
    pageCount: 10,
    tags: ['Aide', 'Justice', 'Gratuité', 'Accès'],
  },
];
